app_recipes/urls.py
from django.urls import path, include
from .views import ai_recipe
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('recipes/', views.recipes, name='recipes'),
    path('recipes/<int:recipe_id>', views.recipe, name='recipe'),
    path('search/', views.search, name='search'),
    path('generate/', ai_recipe, name='generate'),
    path('like_recipe/<int:recipe_id>/', views.like_recipe, name='like_recipe'),
    path('myrecipes/', views.RecipesByUserListView.as_view(), name='my-recipes'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

project_recipes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ai-recipes/', include("app_recipes.urls")),
    path('', RedirectView.as_view(url='ai-recipes/'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_recipes/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User


class Recipe(models.Model):
    name = models.CharField(max_length=200)
    cuisine = models.CharField(max_length=200, blank=True, null=True)
    ingredients = models.CharField(max_length=200)
    instructions = models.TextField()
    image_file = models.ImageField(upload_to='media/images/', blank=True, null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    user = models.ForeignKey(User, related_name='user', on_delete=models.SET_NULL, null=True, blank=True)
    likes = models.ManyToManyField(User, related_name='liked_recipes', blank=True)

    def like_count(self):
        return self.likes.count()

    def __str__(self):
        return str(self.name)

    def save(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        if user:
            self.user = user
        super().save(*args, **kwargs)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>A.I. recipes</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  
</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light static-top mb-5 shadow">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">
      <!-- <img src="templates/android-chrome-512x512_LVnVIjk.png" alt="Logo"> -->
      Powered by A.I.</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'generate' %}">Generate recipe</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'recipes' %}">All recipes</a>
        </li>
      </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="#">
              <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
              </svg>
            {{ user.get_username }}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'my-recipes'%}">My recipes</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'logout'%}?next=/ai-recipes">Logout</a></li>   
          {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'login'%}?next={{request.path}}">Login</a></li>   
          {% endif %}
          {% if not user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'register'%}">Register</a></li>
          {% endif %}
        </ul>
      <form class="form-inline my-2 my-lg-0" action="{% url 'search' %}" method="get">
        <input class="form-control mr-sm-2" type="search" placeholder="Enter topics or keywords" aria-label="Search" name="query">
        <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

<div class="container">
{% block content %}{% endblock %}
</div>


  {% comment %} <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'generate' %}">Generate recipe</a></li>
          <li><a href="{% url 'recipes' %}">All recipes</a></li>
        </ul>
            <form action="{% url 'search' %}" method="get" class="form-inline my-2 my-md-0">
            <input name="query" class="form-control" type="text" placeholder="Search">
            </form>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div> {% endcomment %}
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  
  </body>
</html>

templates/generate_form.html
{% extends 'base.html' %}

{% block content %}
  <h2>Create a Recipe</h2>
  <form method="post" class="my-form" enctype="multipart/form-data">
    {% csrf_token %}
    <ul class="form-list">
      <li>
        <label for="{{ form.ingredients.id_for_label }}">Enter ingredients:</label>
        {{ form.ingredients }}
      </li>
      <li>
        <label for="{{ form.cuisine.id_for_label }}">Enter cuisine:</label>
        {{ form.cuisine }}
      </li>
    </ul>
    <button type="submit">Create Recipe</button>
  </form>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Recipes by Artificial Intelligence</h1>
  <p>Generate recipe from chosen ingredient and cuisine!</p>
  <p>Or you can search one from {{ num_recipes }} already generated recipes <a href="{% url 'recipes' %}">here.</a> </p>
{% endblock %}

templates/loading_screen.html
<div id="loading-screen">
    <div class="loading-spinner"></div>
    <p>Loading...</p>
</div>

templates/my_recipes.html
{% extends "base.html" %}

{% block content %}
    <h1>My generated recipes</h1>

    {% if object_list %}
    <ul>
      {% for recipe in object_list %} 
      <li>
        <a href="{% url 'recipe' recipe.pk %}">{{ recipe.name }}</a> ({{ recipe.user }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>You haven't generated any recipes yet.</p>
    {% endif %}       
{% endblock %}

templates/recipe.html
{% extends "base.html" %}

{% block content %}
    {% load static %}
    <div class="container recipe">
        {% if recipe.image_file %}
            <img src="{{ recipe.image_file.url }}" style="margin-bottom: 20px;">
        {% else %}
            <img src="{% static 'media/images/default.jpeg' %}" style="margin-bottom: 20px;">
        {% endif %}

        <p>Likes: {{ recipe.like_count }}</p>
        <div class="button-group">
            <div class="like-button">
                
                {% if user.is_authenticated %}
                    <form action="{% url 'like_recipe' recipe.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" name="recipe_id" value="{{ recipe.id }}" class="btn btn-primary btn-lm">Like</button>
                    </form>
                {% else %}
                    <p><a href="{% url 'login' %}">Login to like this recipe.</a></p>
                {% endif %}
            </div>

            <div class="share-button">
                <button id="shareButton" class="btn btn-secondary btn-lm">Share</button>
                <input type="text" id="recipeUrlInput" style="display: none;" value="{{ request.build_absolute_uri }}">
            </div>
        </div>

        <script>
            document.getElementById("shareButton").addEventListener("click", function() {
                var recipeUrlInput = document.getElementById("recipeUrlInput");
                recipeUrlInput.style.display = "block";
                recipeUrlInput.select();
                document.execCommand("copy");
                recipeUrlInput.style.display = "none";
                alert("Recipe URL copied!");
            });
        </script>

        <br/>
        <br/>
        <h4>{{ recipe.name }}</h4>
        <h6>Recipe asked by: {{ recipe.user }}</h6>
        <hr/>
        <p>{{ recipe.instructions|linebreaksbr|safe }}</p>
        <hr/>
        <br/>
        <h5>We also have these recipes by {{ recipe.user }}:</h5>
        {% for r in recipe.user.recipe_set.all %}
            <li><a href="{% url 'recipe' r.id %}">{{ r.name }}</a></li> 
        {% endfor %}
    </div>
{% endblock %}

templates/recipe_and_image.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-5">
    <div class="row">
      <div class="col-md-6">
        <h4>{{ title|safe }}</h4>
        <br></br>
        <p>{{ recipe|linebreaksbr|safe }}</p>
      </div>
      <div class="col-md-6">
        <!-- <h3>Generated Image:</h3> -->
        <img src="data:image/png;base64,{{ image_base64 }}" alt="Generated Image" width="256" height="256">
      </div>
    </div>
  </div>
{% endblock %}

templates/recipe_list.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8">
            <h2 class="mb-3">Find a Recipe</h2>
            <form method="get">
                {% csrf_token %}
                <div class="form-group">
                    <label for="ingredient">Enter an ingredient:</label>
                    <input type="text" name="ingredient" class="form-control" id="ingredient" placeholder="e.g. chicken, broccoli, pasta" value="{{ request.GET.ingredient }}">
                    <label for="ingredient">Enter an cuisine:</label>
                    <input type="text" name="cuisine" class="form-control" id="cuisine" placeholder="e.g. italian, asian, french" value="{{ request.GET.cuisine }}">
                </div>
                <button type="submit" class="btn btn-primary">Search</button>
            </form>
        </div>
    </div>
    {% if recipe_suggestions %}
    <div class="row mt-5">
        <div class="col-md-8">
            <h3 class="mb-3">Recipe Suggestions:</h3>
            <p>{{ recipe_suggestions|safe }}</p>
            {% if image %}
            <img src="{{ image.url }}" alt="Generated Recipe Image">
            {% endif %}
        </div>
    </div>
    {% endif %}
    {% if recipes %}
    <div class="row mt-5">
        <div class="col-md-8">
            <h3 class="mb-3">Recipes:</h3>
            <ul class="list-group">
                {% for recipe in recipes %}
                <li class="list-group-item">{{ recipe.name }} <a href="{{ recipe.get_absolute_url }}">View Recipe</a></li>
                {% empty %}
                <p>No recipes found.</p>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

templates/recipes.html
{% extends "base.html" %}

{% block content %}

  {% load static %}
  <h1>List of recipes generated by A.I.</h1></br>
  {% if recipes %}
  <div class="row">
    {% for recipe in recipes %}
      <div class="col-md-4 d-flex align-items-stretch">
        <div class="card mb-4 shadow-sm">
          {% if recipe.image_file %}
            <img src="{{ recipe.image_file.url }}" class="card-img-top" alt="...">
          {% else %}
            <img src="{% static 'images/default.jpeg' %}" class="card-img-top">
          {% endif %}
          <div class="card-body">
            <h6 class="card-subtitle mb-2 text-muted">{{ recipe.user }}</h6>
            <p class="card-text"><a href="{{ recipe.id }}">{{ recipe.name }}</a></p>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  {% else %}
    <p>There is no recipes.</p>
  {% endif %}

{% endblock %}

templates/recipes_all.html
{% if all_recipes %}
    <div class="row mt-5">
        <div class="col-md-8">
            <h3 class="mb-3">All Recipes:</h3>
            <ul class="list-group">
                {% for recipe in all_recipes %}
                <li class="list-group-item">{{ recipe.name }} <a href="{{ recipe.get_absolute_url }}">View Recipe</a></li>
                {% empty %}
                <p>No recipes found.</p>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endif %}

templates/register.html
{% extends "base.html" %}

<!-- {% block "title" %}Registracija{% endblock %} -->

{% block content %}

    <div class="container register">
        <h3>Registracija</h3><br/>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Vartotojo vardas</label>
                <input name="username" type="text" class="form-control" id="username" aria-describedby="usernameHelp">
                <small id="usernameHelp" class="form-text text-muted">Iki 150 simbolių.</small>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">El. paštas</label>
                <input name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <small id="emailHelp" class="form-text text-muted">Nesidalinsime su niekuo, nesiųsime jokio spamo.
                    Reikalingas naujam slaptažodžiui išsiųsti. </small>
            </div>
            <div class="form-group">
                <label for="password">Slaptažodis</label>
                <input name="password" type="password" class="form-control" id="password" aria-describedby="pwdHelp">
                <small id="pwdHelp" class="form-text text-muted">Ne mažiau, kaip 8 simboliai. Negali būti vien tik
                    skaičiai</small>
            </div>
            <div class="form-group">
                <label for="password2">Pakartoti slaptažodį</label>
                <input name="password2" type="password" class="form-control" id="password2" aria-describedby="pwd2Help">
            </div>
            <button type="submit" class="btn btn-primary register-button">Registruotis</button>
        </form>
        <p>Jeigu užsiregistravote anksčiau, <a href="{% url 'login' %}"><strong>prisijunkite.</strong></a></p>
    </div>

{% endblock %}

templates/search.html
{% extends "base.html" %}

{% block content %}
  <h1>Results for "{{query}}" :</h1>
  </br>
  {% if recipes %}
  <ul>
    {% for recipe in recipes %}
      <li>
        <a href="{% url 'recipe' recipe.id %}">{{ recipe.name }}</a> ({{recipe.user}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Oops. Nothing was found :(</p>
  {% endif %}

  {% endblock %}